In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

# Question 1: Version of Pandas


In [2]:
pd.__version__

'1.3.4'

In [4]:
df = pd.read_csv('raw.githubusercontent.com_alexeygrigorev_datasets_master_housing.csv')

# Question 2: Number of columns in the dataset


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [6]:
df.shape

(20640, 10)

# Question 3: Select columns with missing data


In [7]:
df['longitude'].isna().sum()

0

In [8]:
for i in df.columns:
    if df[i].isna().sum()>0:
        print(i)

total_bedrooms


# Question 4: Number of unique values in the 'ocean_proximity' column


In [9]:
df['ocean_proximity'].nunique()

5

In [10]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [11]:
df['ocean_proximity'].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

# Question 5: Average value of the 'median_house_value' for the houses near the bay


In [12]:
df[df['ocean_proximity']=='NEAR BAY']['median_house_value'].mean()

259212.31179039303

# Question 6: Has the mean value changed after filling missing values?
Calculate the average of total_bedrooms column in the dataset.

Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

Now, calculate the average of total_bedrooms again.

Has it changed?


In [13]:
df['total_bedrooms'].mean()

537.8705525375618

In [15]:
df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].mean())

In [16]:
df['total_bedrooms'].mean()

537.8705525375639

# Questions 7: Value of the last element of w
Select all the options located on islands.

In [73]:
df1 = df[df['ocean_proximity']=='ISLAND']

Select only columns housing_median_age, total_rooms, total_bedrooms.

In [74]:
df2 = df1[['housing_median_age','total_rooms','total_bedrooms']]

In [75]:
df2

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

Get the underlying NumPy array. Let's call it X.

In [76]:
X = df2[['housing_median_age','total_rooms','total_bedrooms']].values

In [77]:
X.shape

(5, 3)

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [78]:
XT = X.T

In [79]:
XTX = XT.dot(X)

In [80]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [81]:
np.matmul(XT,X)

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

Compute the inverse of XTX.

In [82]:
XTX_inverse = np.linalg.inv(XTX)

In [83]:
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

Create an array y with values [950, 1300, 800, 1000, 1300].

In [84]:
y =  np.array([950, 1300, 800, 1000, 1300])

In [85]:
y

array([ 950, 1300,  800, 1000, 1300])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [86]:
Int_Mul = np.matmul(XTX_inverse,XT)

In [88]:
w=np.matmul(Int_Mul,y)

What's the value of the last element of w?

In [89]:
w

array([23.12330961, -1.48124183,  5.69922946])

### 5.69922946